### ISSUE TITLE
Customer support is too slow EDIT: closed

### ISSUE THREAD

**Issue by SamCyanide** [cory2067/ClickActions#3]
I opened a ticket 28 seconds ago, and still haven't received a reply! Unacceptable!

**Comment by SamCyanide** [comment]
EDIT: how do I edit?

**Comment by cory2067** [comment]
edit

**Comment by SamCyanide** [comment]
I'm unsubscribing from this subreddit by clicking the "unsubscribe" button located in the right hand sidebar.

**Comment by SamCyanide** [comment]
edit: this isnt reddit

**Comment by cory2067** [comment]
here havE a carma,
